-
    label:  "Страницы"
    action: "content:index"
    position: "first"
    pages:
        -
            label:  Общие
            action: pages:general
        -
            label:  Дополнительно
            action: pages:additional