blocks:
    -
        name: NSCmsBundle:Blocks:contentBlock
        title: Текстовый блок
        template: NSCmsBundle:Blocks:contentBlock.phtml.twig
        settingsFormClass: NS\CmsBundle\Block\Settings\ContentBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\ContentBlockSettingsModel

    -
        name: NSCmsBundle:Blocks:menuBlock
        title: Блок меню
        template: NSCmsBundle:Blocks:menuBlock.phtml.twig
        settingsFormClass: NS\CmsBundle\Block\Settings\MenuBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\MenuBlockSettingsModel
        cache:
            entities: [NS\CmsBundle\Entity\Page]

    -
        name: NSCmsBundle:Blocks:mapBlock
        title: Блок карты
        template: NSCmsBundle:Blocks:mapBlock.phtml.twig
        settingsFormClass: NS\CmsBundle\Block\Settings\MapBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\MapBlockSettingsModel
