blocks:
    -
        name: NSCmsBundle:Blocks:contentBlock
        title: Текстовый блок
        form: "ns_cmsbundle_blockcontenttype"
        template: NSCmsBundle:Blocks:contentBlock.phtml.twig
        settingsFormClass: NS\CmsBundle\Block\Settings\ContentBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\ContentBlockSettingsModel

    -
        name: NSCmsBundle:Blocks:menuBlock
        title: Блок меню
        form: "ns_cmsbundle_blockmenutype"
        template: NSCmsBundle:Blocks:menuBlock.phtml.twig
        settingsFormClass: NS\CmsBundle\Block\Settings\MenuBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\MenuBlockSettingsModel
        cache:
            entities: [NS\CmsBundle\Entity\Page]
