ns_cms_page:
    pattern:  '/page/{id}'
    defaults: { _controller: NSCmsBundle:Pages:page }
    requirements: { id: \d+ }

ns_cms_page_name_long:
    pattern:  '/page/{name}'
    defaults: { _controller: NSCmsBundle:Pages:pageName }

ns_cms_page_name:
    pattern:  '/{name}'
    defaults: { _controller: NSCmsBundle:Pages:pageName }

ns_cms_main:
    pattern: '/'
    defaults: { _controller: NSCmsBundle:Pages:main }

ns_cms_block:
    pattern:  '/block/{blockId}/{pageId}'
    defaults: { _controller: NSCmsBundle:Pages:block }
