parameters:
    ns_cms.form.element.page_select_type.class: 'NS\CmsBundle\Form\Element\PageSelectType'
    ns_cms.form.type.template_path.class:       'NS\CmsBundle\Form\Type\TemplatePathType'
    ns_cms.repository.blocktype.class:          'NS\CmsBundle\Entity\BlockTypeRepository'
    ns_cms.repository.block.class:              'NS\CmsBundle\Entity\BlockRepository'
    ns_cms.repository.block.factory_argument:   'NSCmsBundle:Block'
    ns_cms.repository.page.class:               'NS\CmsBundle\Entity\PageRepository'
    ns_cms.repository.page.factory_argument:    'NSCmsBundle:Page'
    ns_cms.repository.template.class:           'NS\CmsBundle\Entity\TemplateRepository'
    ns_cms.service.page.class:                  'NS\CmsBundle\Service\PageService'
    ns_cms.service.template.class:              'NS\CmsBundle\Service\TemplateService'
    ns_cms.manager.template.class:              'NS\CmsBundle\Manager\TemplateManager'
    ns_cms.manager.block.class:                 'NS\CmsBundle\Manager\BlockManager'
    ns_cms.twig.extension.area.class:           'NS\CmsBundle\Twig\Extension\AreaExtension'

    # search agent classes
    ns_cms.search.content.type:                 'ns_cms:content'
    ns_cms.search.content.model.class:          'NS\CmsBundle\Entity\Block'
    ns_cms.search.content.mapper.class:         'NS\CmsBundle\Search\ContentMapper'
    ns_cms.search.content.repository.class:     'NS\CmsBundle\Search\ContentRepository'

services:
    ns_cms.form.element.page_select_type:
        class: %ns_cms.form.element.page_select_type.class%
        calls:
            - [setPageService, [@ns_cms.service.page]]
        tags:
            -  { name: form.type, alias: ns_cms_form_element_page_select_type }
            
    ns_cms.form.type.template_path:
        class: %ns_cms.form.type.template_path.class%
        calls:
            - [setTemplateRepository, [@ns_cms.repository.template]]
        tags:
            -  { name: form.type, alias: ns_cmsbundle_templatepathtype }

    ns_cms.repository.blocktype:
        class: %ns_cms.repository.blocktype.class%
        arguments: [@ns_admin.service]

    ns_cms.repository.block:
        class: %ns_cms.repository.block.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %ns_cms.repository.block.factory_argument%
        calls:
            - [setTemplateService, [@ns_cms.service.template]]

    ns_cms.repository.page:
        class: %ns_cms.repository.page.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %ns_cms.repository.page.factory_argument%

    ns_cms.service.page:
        class: %ns_cms.service.page.class%
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setPageRepository, [@ns_cms.repository.page]]

    ns_cms.page_service:
        alias: ns_cms.service.page

    ns_cms.repository.template:
        class: %ns_cms.repository.template.class%
        calls:
            - [setContainer, [@service_container]]

    ns_cms.service.template:
        class: %ns_cms.service.template.class%
        calls:
            - [setTemplateRepository, [@ns_cms.repository.template]]

    ns_cms.service.template_location:
        class: 'NS\CmsBundle\Service\TemplateLocationService'
        arguments: [@templating.name_parser, @templating.locator, @kernel]

    ns_cms.manager.template:
        class: %ns_cms.manager.template.class%
        calls:
            - [setTemplateRepository, [@ns_cms.repository.template]]
            - [setTemplateLocationService, [@ns_cms.service.template_location]]

    ns_cms.manager.block:
        class: %ns_cms.manager.block.class%
        calls:
            - [setBlockRepository, [@ns_cms.repository.block]]
            - [setBlockTypeRepository, [@ns_cms.repository.blocktype]]

    ns_cms.twig.extension.area:
        class: %ns_cms.twig.extension.area.class%
        tags:
            - { name: twig.extension }

    # Content search agent
    ns_cms.search.content.agent:
        class: %ns_search.agent.class%
        arguments:
            - %ns_cms.search.content.type%
            - %ns_cms.search.content.model.class%
            - @ns_cms.search.content.mapper
            - @ns_cms.search.content.repository
        tags:
            - { name: ns_search.agent }

    ns_cms.search.content.mapper:
        class: %ns_cms.search.content.mapper.class%
        arguments:
            - @ns_cms.manager.block

    ns_cms.search.content.repository:
        class: %ns_cms.search.content.repository.class%
        arguments:
            - @ns_cms.repository.block